name = "tiny-glade-72fa"
main = "index.js"
compatibility_date = "2026-04-30"
 
[[d1_databases]]
binding = "MY_MMM"
database_name = "mm"
database_id = "e5400dde-3ef0-4d6e-ab99-0f68688d20b2"
preview_database_id = "e5400dde-3ef0-4d6e-ab99-0f68688d20b2"

[[kv_namespaces]]
binding = "bbb"
id = "075caae527884570bad346b6c3cf5abf"

[[services]]
binding = "nnn"
service = "wandering-river-7d75"
environment = "production"

[[services]]
binding = "cvvv"
service = "jolly-disk-5d37"
environment = "production"

[[durable_objects.bindings]]
name = "CHATDO"
class_name = "ChatDO"

[[migrations]]
tag = "v1"
new_classes = ["ChatDO"]
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

